#!/usr/bin/env python3
"""Runs the chaos scenarios against the container stack and writes the failure matrix.

  scripts/chaos/run.py                 # everything (builds and starts the stack, tears it down at the end)
  scripts/chaos/run.py F01 F05         # only these
  scripts/chaos/run.py --keep          # leave the stack running
  scripts/chaos/run.py --no-build      # reuse the images
"""
import os
import shutil
import sys
import time
import traceback

sys.path.insert(0, os.path.dirname(__file__))
from lib import DIAGNOSTICS, ROOT, Fixture, Stack, check_invariants, log, warm_up  # noqa: E402
from scenarios import SCENARIOS  # noqa: E402


def main(argv):
    keep = "--keep" in argv
    build = "--no-build" not in argv
    wanted = [a for a in argv if a.startswith("F")]
    chosen = [s for s in SCENARIOS if not wanted or s["id"] in wanted]
    unknown = sorted(set(wanted) - {s["id"] for s in SCENARIOS})
    if unknown:                                               # a mistyped name must not be a run that passes with nothing run
        sys.exit(f"no such scenario: {' '.join(unknown)}")
    stack = Stack()
    results = []
    started = time.time()
    shutil.rmtree(DIAGNOSTICS, ignore_errors=True)            # what is there afterwards is from this run
    try:
        log("starting the platform (chaos tuning)")
        stack.up(build=build)
        warm_up()
        groups = []                                           # (mode, deadline) in order of first appearance, SYNC first
        for sc in sorted(chosen, key=lambda s: s["mode"] != "SYNC"):
            key = (sc["mode"], sc["deadline"] if sc["mode"] == "ASYNC" else "12s")
            if key not in groups:
                groups.append(key)
        for mode, deadline in groups:
            stack.set_mode(mode, deadline)
            for sc in [s for s in chosen if s["mode"] == mode and (mode == "SYNC" or s["deadline"] == deadline)]:
                results.append(run_one(stack, sc))
    except Exception:                                         # the stack did not come up, or could not be healed
        stack.save_logs("run")
        raise
    finally:
        try:
            stack.heal_everything()
        except Exception as e:
            log(f"could not heal the stack: {e}")
        if not keep:
            stack.down()
    write_matrix(results, time.time() - started)
    failed = [r for r in results if not r["pass"]]
    print(f"\n{len(results) - len(failed)}/{len(results)} scenarios passed", flush=True)
    return 1 if failed else 0


def run_one(stack, sc):
    log(f"=== {sc['id']} {sc['title']} [{sc['mode']}]")
    stack.heal_everything()
    fx = Fixture()
    t0 = time.time()
    actual, ok, settle = "", True, 0.0
    try:
        actual = sc["fn"](stack, fx)
        stack.heal_everything()
        if sc["invariants"]:
            inv_ok, msg, settle = check_invariants(stack, fx)
            if not inv_ok:
                ok, actual = False, f"{actual} | INVARIANT VIOLATED: {msg}"
            else:
                actual = f"{actual} | invariants hold (settled in {settle:.0f}s)"
    except AssertionError as e:
        ok, actual = False, f"ASSERTION FAILED: {e}"
    except Exception as e:                                   # a harness or environment problem is also a failure
        ok, actual = False, f"ERROR: {type(e).__name__}: {e}"
        traceback.print_exc()
    finally:
        if not ok:
            stack.save_logs(sc["id"])                        # now: a later scenario may recreate a container
        try:
            stack.heal_everything()
        except Exception as e:
            log(f"heal failed: {e}")
    dt = time.time() - t0
    log(f"{'PASS' if ok else 'FAIL'} {sc['id']} in {dt:.0f}s: {actual}")
    return dict(id=sc["id"], title=sc["title"], mode=sc["mode"], expected=sc["expected"], actual=actual,
                seconds=round(dt), settle=round(settle), **{"pass": ok})


def write_matrix(results, total):
    path = os.path.join(ROOT, "docs", "failure-matrix.md")
    lines = [
        "# Failure matrix (Phase 13)",
        "",
        "Generated by `scripts/chaos/run.py` against the real container stack (Docker Compose, chaos tuning from",
        "`docker-compose.chaos.yml`). Each row injects one failure, observes the platform, repairs the failure, and then",
        "checks the invariants **from the databases and Kafka**. See [resilience.md](resilience.md) for how to read it.",
        "",
        f"Run on {time.strftime('%Y-%m-%d %H:%M')}, {len(results)} scenarios, {round(total / 60)} min total.",
        "",
        "| # | Failure injected | Mode | Expected | Actual | Time | Result |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        lines.append(f"| {r['id']} | {r['title']} | {r['mode']} | {r['expected']} | {r['actual'].replace('|', '/')} | {r['seconds']}s | {'✅' if r['pass'] else '❌'} |")
    lines += ["", "**Invariants checked after every scenario** (unless noted): stock is conserved per product "
              "(`available + reserved = initial`, never negative); reserved stock equals the quantity held by CONFIRMED orders "
              "(nothing stranded, nothing phantom); every order is CONFIRMED or CANCELLED and every saga is final; both outboxes "
              "are fully published; no order is announced as confirmed twice.", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    log(f"wrote {path}")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
