-- Asynchronous, order-level reservation (Phase 10). Independent of the per-item idempotency
-- records used by the synchronous REST reserve: nothing in V1-V3 is changed.

-- The durable outcome of reserving a whole order, keyed by 'order:{orderId}'. Both outcomes are
-- stored, so a duplicate command can never turn an earlier REJECTED into a later RESERVED.
CREATE TABLE order_reservations (
    order_id            UUID                     NOT NULL,
    idempotency_key     VARCHAR(100)             NOT NULL,
    status              VARCHAR(10)              NOT NULL,
    reason              VARCHAR(100),
    rejected_product_id UUID,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_order_reservations PRIMARY KEY (order_id),
    CONSTRAINT uk_order_reservations_key UNIQUE (idempotency_key),
    CONSTRAINT ck_order_reservations_status CHECK (status IN ('RESERVED', 'REJECTED'))
);

CREATE TABLE order_reservation_items (
    id         UUID    NOT NULL,
    order_id   UUID    NOT NULL,
    product_id UUID    NOT NULL,
    quantity   INTEGER NOT NULL,
    CONSTRAINT pk_order_reservation_items PRIMARY KEY (id),
    CONSTRAINT fk_order_reservation_items_order FOREIGN KEY (order_id) REFERENCES order_reservations (order_id),
    CONSTRAINT uk_order_reservation_items UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_reservation_items_quantity CHECK (quantity > 0)
);

-- Events already handled by this service; written in the same transaction as their effect.
CREATE TABLE processed_events (
    event_id     UUID                     NOT NULL,
    consumer     VARCHAR(50)              NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (event_id)
);

-- Transactional outbox for InventoryReserved / InventoryRejected (same design as Order Service's).
CREATE TABLE inventory_outbox (
    seq             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                     NOT NULL,
    aggregate_id    UUID                     NOT NULL,
    event_type      VARCHAR(40)              NOT NULL,
    payload         VARCHAR(100000)          NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at    TIMESTAMP WITH TIME ZONE,
    attempt_count   INTEGER                  NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    locked_until    TIMESTAMP WITH TIME ZONE,
    last_error      VARCHAR(1000),
    CONSTRAINT uk_inventory_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_inventory_outbox_event_type CHECK (event_type IN ('InventoryReserved', 'InventoryRejected')),
    CONSTRAINT ck_inventory_outbox_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_inventory_outbox_due ON inventory_outbox (published_at, next_attempt_at);
CREATE INDEX idx_inventory_outbox_aggregate ON inventory_outbox (aggregate_id, seq);
