-- Transactional outbox: an event is written in the SAME transaction as the state change it
-- describes, then published to Kafka afterwards by a separate publisher. If the process dies
-- between commit and publish, the row is still here and is published after restart.
CREATE TABLE order_outbox (
    seq             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID                     NOT NULL,
    aggregate_id    UUID                     NOT NULL,
    event_type      VARCHAR(40)              NOT NULL,
    payload         VARCHAR(100000)          NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at    TIMESTAMP WITH TIME ZONE,
    attempt_count   INTEGER                  NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    locked_until    TIMESTAMP WITH TIME ZONE,
    last_error      VARCHAR(1000),
    CONSTRAINT uk_order_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_order_outbox_event_type CHECK (
        event_type IN ('OrderCreated', 'OrderConfirmed', 'OrderCancelled')),
    CONSTRAINT ck_order_outbox_attempt_count CHECK (attempt_count >= 0)
);

-- what the publisher scans, and the per-order ordering check
CREATE INDEX idx_order_outbox_due ON order_outbox (published_at, next_attempt_at);
CREATE INDEX idx_order_outbox_aggregate ON order_outbox (aggregate_id, seq);

-- why a saga was cancelled; carried by the OrderCancelled event
ALTER TABLE order_saga ADD COLUMN failure_reason VARCHAR(100);
