#!/usr/bin/env bash
# One-time setup of every secret the platform needs. Creates (never overwrites):
#   .env              database password, admin login, service-to-service secrets  (random values)
#   .secrets/*.pem    the JWT signing key pair
# Both are git-ignored. Run it once, then `docker compose ... up`.
set -euo pipefail
cd "$(dirname "$0")/.."

rand() { openssl rand -hex "${1:-24}"; }

if [[ -f .env ]]; then
  echo ".env exists, leaving it alone"
else
  umask 077
  cat > .env <<ENV
# Generated by scripts/init-secrets.sh. Never commit this file.
POSTGRES_USER=mercury
POSTGRES_PASSWORD=$(rand 16)
ADMIN_EMAIL=admin@mercury.local
ADMIN_PASSWORD=$(rand 12)
ORDER_SERVICE_SECRET=$(rand 24)
PRODUCT_SERVICE_SECRET=$(rand 24)
GRAFANA_ADMIN_PASSWORD=$(rand 12)
MERCURY_VERSION=dev
ORDER_RESERVATION_MODE=SYNC
ENV
  echo "wrote .env (admin login: admin@mercury.local, password inside .env)"
fi
scripts/generate-jwt-keys.sh
