#!/usr/bin/env bash
# One-time setup of every secret the platform needs. Creates (never overwrites):
#   .env              database password, admin login, service-to-service secrets  (random values)
#   .secrets/*.pem    the JWT signing key pair
# Both are git-ignored. Run it once, then `docker compose ... up`.
set -euo pipefail
cd "$(dirname "$0")/.."

rand() { openssl rand -hex "${1:-24}"; }

if [[ -f .env ]]; then
  echo ".env exists, leaving it alone"
else
  umask 077
  cat > .env <<ENV
# Generated by scripts/init-secrets.sh. Never commit this file.
POSTGRES_USER=mercury
POSTGRES_PASSWORD=$(rand 16)
ADMIN_EMAIL=admin@mercury.local
ADMIN_PASSWORD=$(rand 12)
ORDER_SERVICE_SECRET=$(rand 24)
PRODUCT_SERVICE_SECRET=$(rand 24)
GRAFANA_ADMIN_PASSWORD=$(rand 12)
MERCURY_VERSION=dev
ORDER_RESERVATION_MODE=SYNC
ENV
  echo "wrote .env (admin login: admin@mercury.local, password inside .env)"
fi
scripts/generate-jwt-keys.sh

# The private key is mode 640 and stays owned by whoever runs this script. The user-service runs as uid/gid 10001, which on
# Linux is neither that owner nor in the file's group, so compose gives that one container the key's own group as well
# (group_add in docker-compose.yml). Docker Desktop on macOS hides the problem, a Linux host does not. Recorded in .env, also
# when .env already existed.
gid="$(scripts/lib/file-gid.sh .secrets/jwt-private.pem)"
( umask 077
  { grep -v '^JWT_PRIVATE_KEY_GID=' .env || true; echo "JWT_PRIVATE_KEY_GID=$gid"; } > .env.tmp )
mv .env.tmp .env
echo "the user-service will read .secrets/jwt-private.pem through its group ($gid)"
